pipeline {
    agent { label 'build' }
    stages {
        stage('pre-requisites-install') {
            steps {
                sh './app_code/simple-java-maven-app/jenkins/scripts/pre-install.sh'
            }
        }
        stage('Build') {
            steps {
                sh 'cd app_code/simple-java-maven-app;mvn -B -DskipTests clean package'
            }
        }
        stage('Test') {
            steps {
                sh 'cd app_code/simple-java-maven-app;mvn test'
            }
        }
        stage('Deliver') {
            steps {
                sh './app_code/simple-java-maven-app/jenkins/scripts/deliver.sh'
            }
        }
    }
}
