pipeline {
    agent any
    stages {
        stage('pre-requisites-install') {
            steps {
                sh '/var/lib/jenkins/workspace/simple-java-maven-app/app_code/simple-java-maven-app/jenkins/scripts/pre-install.sh'
            }
        }
        stage('Build') {
            steps {
                sh 'mvn -B -DskipTests clean package'
            }
        }
        stage('Test') {
            steps {
                sh 'mvn test'
            }
            post {
                always {
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }
        stage('Deliver') {
            steps {
                sh './scripts/deliver.sh'
            }
        }
    }
}
