pipeline {
    agent any
    stages {
        stage('pre-requisites-install') {
            steps {
                sh './app_code/simple-java-maven-app/jenkins/scripts/pre-install.sh'
            }
        }
        stage('Build') {
            steps {
                sh 'cd app_code/simple-java-maven-app;mvn -B -DskipTests clean package'
            }
        }
        stage('Test') {
            steps {
                sh 'cd app_code/simple-java-maven-app;mvn test'
            }
            post {
                always {
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }
        stage('Deliver') {
            steps {
                sh './app_code/simple-java-maven-app/jenkins/scripts/deliver.sh'
            }
        }
    }
}
